import { Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>fasafe</title>
        <link rel="icon" href={"/money-bag.png"} />
      </head>
      <ClerkProvider>
        <body className={outfit.className}>{children}</body>
      </ClerkProvider>
    </html>
  );
}
